name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: [main]
    paths:
      - .github/workflows/metrics.yml
      - README.md
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          config_timezone: Europe/Amsterdam
          base: "header, community, metadata"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
